# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.18.3]

    steps:
    # - uses: actions/checkout@master
    # - run: |
    #     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    #     sudo apt install ./google-chrome-stable_current_amd64.deb -y
    - uses: nanasess/setup-chromedriver@master
      with:
       chromedriver-version: '86.0.4240.22'
       args: "headless"
    - run: |
       export DISPLAY=:99
       chromedriver --url-base=/ &
       sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
    - run: |
        npm ci
        npm run build --if-present
        ./node_modules/.bin/wdio wdio.conf.js
      env:
        CI: true
